In [1]:
import cv2
import numpy as np

In [16]:
image = cv2.imread('image.jpg')

In [17]:
image.shape

(225, 225, 3)

In [18]:
image.resize(256, 256, 3)

In [19]:
print(image)

[[[ 0  1  0]
  [ 0  1  0]
  [ 0  2  0]
  ...
  [31 27 26]
  [36 32 31]
  [26 22 21]]

 [[40 36 35]
  [25 23 23]
  [26 24 24]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [20]:
cv2.imwrite('image2.jpg', image)

True